// Generated by CoffeeScript 1.9.3
var Promise, Start, Stop, Update, context, getPromise, input, jsonfile, kavconfig, startcall;

jsonfile = require('jsonfile');

Start = require('./../src/context').start;

Stop = require('./../src/context').stop;

Update = require('./../src/context').update;

Promise = require('bluebird');

context = {};

input = {
  "baseUrl": "http://192.168.122.217:5000",
  "bInstalledPackages": true,
  "bFactoryPush": false,
  "service": {
    "name": "kaspersky",
    "config": {}
  }
};

getPromise = function() {
  return new Promise(function(resolve, reject) {
    return resolve();
  });
};

startcall = function(input) {
  return getPromise().then((function(_this) {
    return function(resp) {
      jsonfile.writeFileSync("/tmp/start-input.json", input, {
        spaces: 2
      });
      return Start(input);
    };
  })(this))["catch"]((function(_this) {
    return function(err) {
      return console.log("Start err ", err);
    };
  })(this)).then((function(_this) {
    return function(resp) {
      jsonfile.writeFileSync("/tmp/start-output.json", resp, {
        spaces: 2
      });
      return console.log("result from Start:\n ", JSON.stringify(resp));
    };
  })(this)).done;
};

kavconfig = {
  "KASPERSKY_SCAN_TIMEOUT": 20000,
  "KASPERSKY_MAX_SESSIONS": 10,
  "HTTP_AV_SCAN": false,
  "KASPERSKY_HTTP_UPLOAD": false,
  "KASPERSKY_HTTP_DOWNLOAD": false,
  "MAIL_AV_SCAN": false,
  "KASPERSKY_SMTP": false,
  "KASPERSKY_POP3": false,
  "KASPERSKY_IMAP": false
};

input.service.config = kavconfig;

startcall(input);
