// Generated by CoffeeScript 1.9.3
(function() {
  var Promise, PutConfig, Start, Stop, Update, UpdateKAVRepo, Validate, assert, getCorenovaID, getPromise, needle, schema_kaspersky, validate;

  validate = require('json-schema').validate;

  assert = require('assert');

  Promise = require('bluebird');

  needle = Promise.promisifyAll(require('needle'));

  schema_kaspersky = require('./schema').kaspersky;

  getPromise = function() {
    return new Promise(function(resolve, reject) {
      return resolve();
    });
  };

  getCorenovaID = function(baseUrl) {
    return needle.getAsync(baseUrl + "/corenova", {
      json: true
    }).then((function(_this) {
      return function(resp) {
        var corenovas;
        if (resp[0].statusCode !== 200) {
          throw new Error('invalidStatusCode');
        }
        corenovas = resp[0].body;
        return corenovas[0].id;
      };
    })(this))["catch"]((function(_this) {
      return function(err) {
        throw err;
      };
    })(this));
  };

  UpdateKAVRepo = function(baseUrl) {
    var config, data, kavpersonality, kavrepo, personality, ref;
    config = require('../package.json').config;
    kavrepo = (ref = config.kav_repo) != null ? ref : "http://repo.dev.intercloud.net/kav";
    data = new Buffer(kavrepo).toString('base64');
    personality = {};
    personality.personality = [];
    kavpersonality = {
      "path": "/etc/kav_repo",
      "contents": data,
      "postxfer": "/usr/sbin/kav_update"
    };
    personality.personality.push(kavpersonality);
    return needle.postAsync(baseUrl + "/personality", personality, {
      json: true
    }).then((function(_this) {
      return function(resp) {
        if (resp[0].statusCode !== 200) {
          throw new Error('invalidStatusCode');
        }
        return true;
      };
    })(this))["catch"]((function(_this) {
      return function(err) {
        throw err;
      };
    })(this));
  };

  PutConfig = function(baseUrl, id, config) {
    return needle.putAsync(baseUrl + ("/corenova/" + id + "/transform/include"), config, {
      json: true
    }).then((function(_this) {
      return function(resp) {
        if (resp[0].statusCode !== 200) {
          throw new Error('invalidStatusCode');
        }
        return config;
      };
    })(this))["catch"]((function(_this) {
      return function(err) {
        throw err;
      };
    })(this));
  };

  Start = function(context) {
    var config;
    if (!(context.bInstalledPackages && context.service.name && context.service.config)) {
      throw new Error('openvpn-storm.Start missingParams');
    }
    config = context.service.config;
    config.HAVE_KASPERSKY = true;
    return getPromise().then((function(_this) {
      return function(resp) {
        return UpdateKAVRepo(context.baseUrl);
      };
    })(this)).then((function(_this) {
      return function(resp) {
        return getCorenovaID(context.baseUrl);
      };
    })(this)).then((function(_this) {
      return function(corenovaid) {
        return PutConfig(context.baseUrl, corenovaid, config);
      };
    })(this)).then((function(_this) {
      return function(resp) {
        return context;
      };
    })(this))["catch"]((function(_this) {
      return function(err) {
        throw err;
      };
    })(this));
  };

  Stop = function(context) {
    var config;
    if (!(context.bInstalledPackages && context.service.name && context.service.config)) {
      throw new Error('openvpn-storm.Start missingParams');
    }
    config = context.service.config;
    config.HAVE_KASPERSKY = false;
    return getPromise().then((function(_this) {
      return function(resp) {
        return getCorenovaID(context.baseUrl);
      };
    })(this)).then((function(_this) {
      return function(corenovaid) {
        return PutConfig(context.baseUrl, corenovaid, config);
      };
    })(this)).then((function(_this) {
      return function(resp) {
        return context;
      };
    })(this))["catch"]((function(_this) {
      return function(err) {
        throw err;
      };
    })(this));
  };

  Update = function(context) {
    var config;
    if (!(context.bInstalledPackages && context.service.name && context.service.config)) {
      throw new Error('openvpn-storm.Start missingParams');
    }
    config = context.service.config;
    return getPromise().then((function(_this) {
      return function(resp) {
        return getCorenovaID(context.baseUrl);
      };
    })(this)).then((function(_this) {
      return function(corenovaid) {
        return PutConfig(context.baseUrl, corenovaid, config);
      };
    })(this)).then((function(_this) {
      return function(resp) {
        return context;
      };
    })(this))["catch"]((function(_this) {
      return function(err) {
        throw err;
      };
    })(this));
  };

  Validate = function(config) {
    var chk;
    if (config == null) {
      throw new Error("kaspersky.Validate - invalid input");
    }
    chk = validate(config, schema_kaspersky);
    console.log('server validate result ', chk);
    if (!chk.valid) {
      throw new Error("server schema check failed" + chk.valid);
      return false;
    } else {
      return true;
    }
  };

  module.exports.start = Start;

  module.exports.stop = Stop;

  module.exports.update = Update;

  module.exports.validate = Validate;

}).call(this);
